### ISSUE TITLE
Fails if braces are not balanced in a `codehigh` environment

### ISSUE THREAD

**Issue by dbitouze** [lvjr/codehigh#1]
`codehigh` fails if braces are not balanced in a `codehigh` environment:
```latex
\documentclass{article}
\usepackage{codehigh}
\begin{document}

This stuff will be at the end of the preamble:

\begin{codehigh}[language=latex/latex3]
\AddToHook{begindocument/before}{
\end{codehigh}

The stuff:

\begin{codehigh}[language=latex/latex3]
...
\end{codehigh}

We close the "at the end of the preamble" part:

\begin{codehigh}[language=latex/latex3]
}
\end{codehigh}

\end{document}
```

**Comment by lvjr** [comment]
At this time, `codehigh` environment is not a real `verbatim` environment, but an environment similar to that defined by `\NewEnviron` command. I need to improve the environment.

**Comment by lvjr** [comment]
This bug has been fixed in commit https://github.com/lvjr/codehigh/commit/88d17e2463f580f637e516642b6f64b7785bad1e.
