### ISSUE TITLE
How to use codehigh in .dtx file?

### ISSUE THREAD

**Issue by note286** [lvjr/codehigh#10]
This is `test.dtx` file.
```latex
% \iffalse
%<*driver>
\ProvidesFile{test.dtx}
%</driver>
%<class>\NeedsTeXFormat{LaTeX2e}
%<class>\ProvidesClass{test}[2022/11/22 v1.0.0 Test]
%<*driver>
\documentclass{l3doc}
\usepackage{codehigh}
\begin{document}
\DocInput{\jobname.dtx}
\end{document}
%</driver>
% \fi
% This is document.
% \begin{codehigh}
% \documentclass{test}
% \begin{document}
% Test
% \end{document}
% \end{codehigh}
% This is document.
% \section{Implementation}
%    \begin{macrocode}
%<*class>
\LoadClass{ctexart}
%</class>
%    \end{macrocode}
% \Finale
\endinput
```

This is `test.ins` file.
```latex
\input docstrip
\askforoverwritefalse
\preamble
\endpreamble
\postamble
\endpostamble
\keepsilent
\generate{\file{\jobname.cls}{\from{\jobname.dtx}{class}}}
\nopreamble
\nopostamble
\endbatchfile
```

With `pdflatex test.dtx` and `pdflatex test.ins`, we get `test.cls` as below:
```latex
%%
%% This is file `test.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% test.dtx  (with options: `class')
%% 
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{test}[2022/11/22 v1.0.0 Test]
\LoadClass{ctexart}
%% 
%%
%% End of file `test.cls'.
```
and `test.pdf` as below:
![image](https://user-images.githubusercontent.com/16207292/203255707-e5196ef7-3fe3-486a-8327-e34f8955ea08.png)

I don't know why `codehigh` recognizes the `%`. According to my understanding, `\DocInput` swallows the `%`. So what is the cause of this situation?

**Comment by lvjr** [comment]
It seems `%` characters are still there when `codehigh` environment is executed. But I know little about `docstrip`, so I am not sure it is a bug of `docstrip` or `codehigh`. Hope @FrankMittelbach has a little time to see this issue?

**Comment by note286** [comment]
I tested `listings` package, and I found the same problem, but `listings` package has a parameter `gobble` that can be set, namely `\lstset{gobble=2}`.

```latex
% \iffalse
%<*driver>
\ProvidesFile{test.dtx}
%</driver>
%<class>\NeedsTeXFormat{LaTeX2e}
%<class>\ProvidesClass{test}[2022/11/22 v1.0.0 Test]
%<*driver>
\documentclass{l3doc}
\usepackage{ninecolors}
\usepackage{listings}
\lstset{
gobble          = 2,
language        = [LaTeX]TeX,
basicstyle      = \small\ttfamily,
backgroundcolor = \color{azure9!25},
keywordstyle    = \color{red6}
}
\begin{document}
\DocInput{\jobname.dtx}
\end{document}
%</driver>
% \fi
% This is document.
% \begin{lstlisting}
% \documentclass{test}
% \begin{document}
% Test
% \end{document}
% \end{lstlisting}
% This is document.
% \section{Implementation}
%    \begin{macrocode}
%<*class>
\LoadClass{ctexart}
%</class>
%    \end{macrocode}
% \Finale
\endinput
```

![image](https://user-images.githubusercontent.com/16207292/203286344-df630d79-0cba-496b-82bb-279a21aed9ed.png)

If don't set `\lstset{gobble=2}`, it will be
![image](https://user-images.githubusercontent.com/16207292/203286607-e11bb8d7-48ea-48a8-864d-a15997fb471e.png)

Can `codehigh` package provide interface like `gobble`? The default configuration provided by `codehigh` package is really beautiful, and I like it very much. It would be appreciated if the author could add this interface.

**Comment by note286** [comment]
I'll give it a try, but my level is limited, and there is a high probability that I can't realize this `gobble` in `codehigh`. Finally, thank you again for your answers.

**Comment by FrankMittelbach** [comment]
beside that you may want (perhaps) something like `\AddToHook{package/doc/after}{ arrange for "gobble=2" as default }` in the package
