### ISSUE TITLE
Add \fakeverb command for tabularray

### ISSUE THREAD

**Issue by lvjr** [lvjr/codehigh#11]
To ease the pain of writing verbatim commands (see https://github.com/lvjr/tabularray/issues/358), I will add `\fakeverb` command to `codehigh` package.

This command will remove the backslashes in the following control symbols before typesetting its content:

| Input | Result | Catcode |
| ----- | ------ | ------- |
| `\\`  | `\`    | 0       |
| `\{`  | `{`    | 1       |
| `\}`  | `}`    | 2       |
| `\#`  | `#`    | 6       |
| `\^`  | `^`    | 7       |
| `\ `  | ` `    | 10      |
| `\%`  | `%`    | 14      |

The argument of `\fakeverb` command need to be enclosed with curly braces. Therefore it could be safely used inside `tabularray` tables and other `LaTeX` commands.

To make it a replacement for `\verb` command, we should not highlight the code inside this command by default.

**Comment by muzimuzhi** [comment]
Looks similar to `\EscVerb` from `fvextra` package.

**Comment by lvjr** [comment]
> Looks similar to `\EscVerb` from `fvextra` package.

Yes, both are based on a similar idea. But not totally the same.
